-- First business table: PIP (a 7-week planning cycle), identified by its code yy_PIP_n.
-- start_date / end_date / status are not edited by the UI yet (status defaults to PREPARATION).
-- H2-oriented DDL; adapt the identity column for MS SQL Server when migrating.

CREATE TABLE pip (
    id         BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    code       VARCHAR(32) NOT NULL,
    start_date DATE,
    end_date   DATE,
    status     VARCHAR(20) NOT NULL,
    CONSTRAINT uq_pip_code UNIQUE (code)
);
