-- PIP detail model: teams (reference data), projects (TCM), requirements (REQ),
-- per-team workloads, per-team dev comments, and per-team PIP capacities.
-- H2-oriented DDL; adapt identity columns/types for MS SQL Server when migrating.

CREATE TABLE team (
    id   BIGINT      GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    CONSTRAINT uq_team_name UNIQUE (name)
);

CREATE TABLE project (
    id          BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tcm_key     VARCHAR(32)  NOT NULL,
    description VARCHAR(1000),
    pip_id      BIGINT       NOT NULL,
    CONSTRAINT fk_project_pip FOREIGN KEY (pip_id) REFERENCES pip (id),
    CONSTRAINT uq_project_pip_tcm UNIQUE (pip_id, tcm_key)
);

CREATE TABLE requirement (
    id         BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    req_key    VARCHAR(32)  NOT NULL,
    description VARCHAR(1000),
    status     VARCHAR(50),
    pm_comment VARCHAR(2000),
    project_id BIGINT       NOT NULL,
    CONSTRAINT fk_requirement_project FOREIGN KEY (project_id) REFERENCES project (id),
    CONSTRAINT uq_requirement_key UNIQUE (req_key)
);

CREATE TABLE workload (
    id             BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id BIGINT       NOT NULL,
    team_id        BIGINT       NOT NULL,
    estimate       DECIMAL(7, 2),
    CONSTRAINT fk_workload_requirement FOREIGN KEY (requirement_id) REFERENCES requirement (id),
    CONSTRAINT fk_workload_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT uq_workload_req_team UNIQUE (requirement_id, team_id)
);

CREATE TABLE dev_comment (
    id             BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id BIGINT        NOT NULL,
    team_id        BIGINT        NOT NULL,
    text           VARCHAR(2000),
    CONSTRAINT fk_devcomment_requirement FOREIGN KEY (requirement_id) REFERENCES requirement (id),
    CONSTRAINT fk_devcomment_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT uq_devcomment_req_team UNIQUE (requirement_id, team_id)
);

CREATE TABLE pip_capacity (
    id       BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pip_id   BIGINT        NOT NULL,
    team_id  BIGINT        NOT NULL,
    capacity DECIMAL(9, 2),
    CONSTRAINT fk_capacity_pip FOREIGN KEY (pip_id) REFERENCES pip (id),
    CONSTRAINT fk_capacity_team FOREIGN KEY (team_id) REFERENCES team (id),
    CONSTRAINT uq_capacity_pip_team UNIQUE (pip_id, team_id)
);

-- Seed the six fixed teams (insertion order = display order).
INSERT INTO team (name) VALUES ('Core'), ('Portal'), ('Process'), ('Assets'), ('API'), ('Document');
