-- Excel import (Slice 1): per-PIP versioning, raw import snapshots, and the diff-derived
-- fields (priority, PIP status) on the live requirement rows. H2-oriented DDL; adapt
-- identity columns / BOOLEAN / TIMESTAMP for MS SQL Server when migrating.

-- Diff-derived fields on the live requirement (recomputed at each import).
ALTER TABLE requirement ADD COLUMN priority INT;
ALTER TABLE requirement ADD COLUMN pip_status VARCHAR(40);

-- Remember manual workload edits so the next import does not overwrite them.
ALTER TABLE workload ADD COLUMN manual_override BOOLEAN DEFAULT FALSE NOT NULL;

-- REQ keys are unique per PIP (enforced in the application layer), not globally:
-- drop the global constraint so the same REQ key could exist in another PIP.
ALTER TABLE requirement DROP CONSTRAINT uq_requirement_key;

-- One row per file deposit (version) for a PIP.
CREATE TABLE excel_import (
    id                BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    pip_id            BIGINT       NOT NULL,
    version_no        INT          NOT NULL,
    original_filename VARCHAR(255),
    imported_at       TIMESTAMP    NOT NULL,
    CONSTRAINT fk_import_pip FOREIGN KEY (pip_id) REFERENCES pip (id),
    CONSTRAINT uq_import_pip_version UNIQUE (pip_id, version_no)
);

-- Raw parsed values of each REQ for a given version (basis for the diff and future rollback).
CREATE TABLE imported_requirement (
    id              BIGINT       GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    excel_import_id BIGINT       NOT NULL,
    req_key         VARCHAR(32)  NOT NULL,
    tcm_key         VARCHAR(32),
    tcm_description VARCHAR(1000),
    req_description VARCHAR(1000),
    pm_comment      VARCHAR(2000),
    priority        INT,
    missing_data    BOOLEAN      DEFAULT FALSE NOT NULL,
    CONSTRAINT fk_imreq_import FOREIGN KEY (excel_import_id) REFERENCES excel_import (id)
);

-- Raw per-team workloads as found in the file for that version.
CREATE TABLE imported_workload (
    id                      BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    imported_requirement_id BIGINT        NOT NULL,
    team_id                 BIGINT        NOT NULL,
    estimate                DECIMAL(7, 2),
    CONSTRAINT fk_imwl_imreq FOREIGN KEY (imported_requirement_id) REFERENCES imported_requirement (id),
    CONSTRAINT fk_imwl_team FOREIGN KEY (team_id) REFERENCES team (id)
);
