-- Marks workload cells whose value was written by the JIRA backlog sync. Cells with
-- jira_locked = true are read-only in the UI; the JIRA sync overrides them on each run
-- (manual_override is also set so imports don't clobber JIRA-sourced values).
-- Kept portable: BOOLEAN like tbd (V5); MS SQL Server target will use BIT.
ALTER TABLE workload ADD COLUMN jira_locked BOOLEAN DEFAULT FALSE NOT NULL;

-- Stores the computed Team Status per (requirement, team) from the JIRA backlog sync.
-- Separate from the workload table because a team can have a Team Status even when it has
-- no story-point entry (e.g. only a Technical Analysis ticket exists).
CREATE TABLE requirement_backlog (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requirement_id BIGINT NOT NULL,
    team_id        BIGINT NOT NULL,
    team_status    VARCHAR(50),
    CONSTRAINT uk_req_backlog  UNIQUE (requirement_id, team_id),
    CONSTRAINT fk_rb_req  FOREIGN KEY (requirement_id) REFERENCES requirement(id),
    CONSTRAINT fk_rb_team FOREIGN KEY (team_id) REFERENCES team(id)
);
